<?php
   include_once('./includes/headerNav.php');
  include "includes/config.php";

?>



<div class="overlay" data-overlay></div>
<!--
    - HEADER
  -->

<header>
  <!-- top head action, search etc in php -->
  <?php require_once './includes/topheadactions.php'; ?>

  <!-- mobile nav in php -->
  <?php require_once './includes/mobilenav.php'; ?>

</header>

<!--
    - MAIN
  -->

<main>

  <div class="product-container">
    <div class="container">
      <!--
          - SIDEBAR
        -->
      <!-- CATEGORY SIDE BAR MOBILE MENU -->
      <?php require_once './includes/categorysidebar.php'; ?>
      <!-- ############################# -->

      <div class="product-box">
        <!-- get id and url for each category and display its dat from table her in this secton -->
        <div class="product-main">

          <h2 class="title">
            Search:
            <?php
              // Get Item name searching for
              if(isset($_POST['search']))
              {
                echo $_POST['search'];
              }
             ?>
          </h2>

          <div class="product-grid">

            <!-- display data from table new products -->

            <?php
            //Very important SEO friendly code generated by myself (practices)

            if(isset($_POST['submit']) AND !(empty($_POST['search'])) OR isset($_POST['catag'])) {

              if(isset($_GET['catag'])) {
                $seacrh_term = mysqli_real_escape_string($conn, $_GET['catag']);
              } else {
                $seacrh_term = mysqli_real_escape_string($conn, $_POST['search']);
              }



            if (isset($_GET['page'])){
              $page = $_GET['page'];
            } else {
              $page = 1;
            }

            // define how much data to show in a page from database
            $limit = 8;
            // define from which row to start extracting data from database
            $offset = ($page - 1) * $limit;

              //making search_term string to array each value separated by space
              $search_term_array = explode(" ",$seacrh_term);

              // Validate and sanitize search terms
              $sanitized_terms = [];
              foreach($search_term_array as $term) {
                  $sanitized_term = InputValidator::validateSearchTerm($term);
                  if ($sanitized_term !== false) {
                      $sanitized_terms[] = $sanitized_term;
                  }
              }

              if (empty($sanitized_terms)) {
                  echo '<div class="alert alert-danger">Invalid search terms.</div>';
                  $search_result = false;
              } else {
                  $array_length = sizeof($sanitized_terms);

                  // Validate offset and limit
                  $offset = InputValidator::validateInt($offset, 0);
                  $limit = InputValidator::validateInt($limit, 1, 50);

                  if ($offset === false) $offset = 0;
                  if ($limit === false) $limit = 12;

                  if($array_length > 1) {
                      // Use prepared statement for multiple terms
                      $search_query = "SELECT * FROM products WHERE products.product_title LIKE ? AND products.product_catag LIKE ? ORDER BY products.product_id DESC LIMIT ?, ?";
                      $term1 = '%' . $sanitized_terms[0] . '%';
                      $term2 = '%' . $sanitized_terms[1] . '%';
                      $search_result = $secureDB->select($search_query, [$term1, $term2, $offset, $limit], 'ssii');
                  } else {
                      // Use prepared statement for single term
                      $search_query = "SELECT * FROM products WHERE products.product_title LIKE ? OR products.product_catag LIKE ? ORDER BY products.product_id DESC LIMIT ?, ?";
                      $term = '%' . $sanitized_terms[0] . '%';
                      $search_result = $secureDB->select($search_query, [$term, $term, $offset, $limit], 'ssii');
                  }
              }
              $new_product_counter = 1;

            // Query used earlier
            // $search_query = "SELECT * FROM PRODUCT WHERE product.name LIKE '%$get_seach_value%' ";
            // $run_search = mysqli_query($connect,$search_query);
            if($search_result && $search_result->num_rows > 0) {


            while ($row = mysqli_fetch_assoc($search_result)) {

            ?>
              <!-- display all category products -->
              <div class="showcase">
                <div class="showcase-banner">
                  <img src="./admin/upload/<?php
                                                      echo $row['product_img']
                                                      ?>" alt="Mens Winter Leathers Jackets" width="300" class="product-img default" />
                  <img src="./admin/upload/<?php
                                                      echo $row['product_img']
                                                      ?>" alt="search result images" width="300" class="product-img hover" />
                  <!-- Applying coditions on dicount and sale tags  -->
                  <!--  -->


                  <div class="showcase-actions">
                    <button class="btn-action">
                      <ion-icon name="heart-outline"></ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="eye-outline">

                      </ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="repeat-outline"></ion-icon>
                    </button>

                    <button class="btn-action">
                      <ion-icon name="bag-add-outline"></ion-icon>
                    </button>
                  </div>
                </div>

                <div class="showcase-content">
                  <a href="./viewdetail.php?id=<?php echo $row['product_id'] ?>&category=<?php $row['category_id'] ?>" class="showcase-category">
                    <?php echo $row['product_title'] ?>
                  </a>

                  <a href="./viewdetail.php?id=<?php echo $row['product_id'] ?>&category=<?php $row['category_id'] ?>">
                    <h3 class="showcase-title">
                      <?php echo $row['product_desc'] ?>
                    </h3>
                  </a>

                  <div class="showcase-rating">
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                    <ion-icon name="star"></ion-icon>
                  </div>

                  <div class="price-box">
                    <p class="price">
                      $<?php echo $row['discounted_price'] ?>
                    </p>
                    <del>
                      $<?php echo $row['product_price'] ?>
                    </del>
                  </div>
                </div>
              </div>

            <?php
              $new_product_counter = $new_product_counter + 1;
             }} else {
              echo "<h4 style='color:red; margin-left:8%;border:1px solid aliceblue'>"."No record found"."</h4>";
            }
             $conn->close();
            ?>

            <!--  -->
          </div>
        </div>
      </div>
    </div>
  </div>

<!--Pagination-->
<div class="pag-cont-search">
<?php
                include "includes/config.php";

               // Pagination btn using php with active effects

                $sql1 = "SELECT * FROM products";
                $result1 = mysqli_query($conn, $sql1) or die("Query Failed.");

                if(mysqli_num_rows($result1) > 0){

                  $total_products = mysqli_num_rows($search_result);
                  $total_page = ceil($total_products / $limit);

                  echo "<div class='pagination'>";

                  for($i=1; $i<=$total_page; $i++){

                    //important this is for active effects that denote in which page you are in current position
                    if($page==$i){
                      $active = "active";
                    }else{
                      $active = "";
                    }

                        echo "<a href='search.php?page={$i}' class='{$active}'>".$i."</a>";
                  }

                }
                echo "</div>";

               } //main if
               else {
                 echo "<h4 style='color:red; margin-left:8%;border:1px solid aliceblue'>"."ERR_Insert on Search"."</h4>";
               }
               ?>

</div>


</main>

<?php require_once './includes/footer.php'; ?>
